In [14]:
import pandas as pd
import numpy as np

In [9]:
df = pd.read_csv("./2022.csv")

In [22]:
df = df.drop('Unnamed: 0', axis = 1).copy()

In [23]:
df

,id,Name,KUCBT Score,Program,Gender
0,KUCBT_2022_1,Susmita Rai,576,BE in Computer Engineering,NaN
1,KUCBT_2022_6,Dipak Kumar Sah,729,BE in Computer Engineering,NaN
2,KUCBT_2022_8,Swechchha Parajuli,539,BE in Computer Engineering,NaN
3,KUCBT_2022_9,Bhuwan Kshetri,592,BE in Civil Engineering (Specialization in Hyd...,NaN
4,KUCBT_2022_11,Siddhartha Jha,580,BE in Civil Engineering (Specialization in Hyd...,NaN
...,...,...,...,...,...
1660,KUCBT_2022_3258,Saan Sainju,532,BArch in Architecture,NaN
1661,KUCBT_2022_3259,Isha Lamichhane,714,BE in Mechanical Engineering(Automobile),NaN
1662,KUCBT_2022_3263,Samikshya Ghimire,652,BE in Geomatics Engineering,NaN
1663,KUCBT_2022_3267,GANGA RAM YADAV,848,BE in Civil Engineering (Specialization in Hyd...,NaN
1664,KUCBT_2022_3269,Ajay Kumar Thing Tamang,550,BE in Mechanical Engineering(Design and Manufa...,NaN

In [36]:
df['Name'] = df['Name'].str.lower()

In [37]:
df.head()

,id,Name,KUCBT Score,Program,Gender
0,KUCBT_2022_1,susmita rai,576,BE in Computer Engineering,NaN
1,KUCBT_2022_6,dipak kumar sah,729,BE in Computer Engineering,NaN
2,KUCBT_2022_8,swechchha parajuli,539,BE in Computer Engineering,NaN
3,KUCBT_2022_9,bhuwan kshetri,592,BE in Civil Engineering (Specialization in Hyd...,NaN
4,KUCBT_2022_11,siddhartha jha,580,BE in Civil Engineering (Specialization in Hyd...,NaN

In [ ]:
name_gender_map = {} #first_name -> gender
first_name_list = []
for index, row in df.iterrows():
    first_name = row['Name'].split(' ')[0]
    if first_name not in name_gender_map:
        while True:
            gender = input(f"Enter gender for {first_name} (m/f): ")
            if gender in ['f','m']:
                name_gender_map[first_name] = gender
                break

Enter gender for susmita (m/f): f
Enter gender for dipak (m/f): m
Enter gender for swechchha (m/f): f
Enter gender for bhuwan (m/f): m
Enter gender for siddhartha (m/f): m
Enter gender for shreya (m/f): f
Enter gender for jenish (m/f): m
Enter gender for hridam (m/f): m
Enter gender for bijay (m/f): m
Enter gender for anubhav (m/f): m
Enter gender for aashish (m/f): m
Enter gender for nitesh (m/f): m
Enter gender for yashoda (m/f): f
Enter gender for nibhrit (m/f): m
Enter gender for prabhat (m/f): m
Enter gender for joshana (m/f): f
Enter gender for prakriti (m/f): f
Enter gender for rusha (m/f): f
Enter gender for priya (m/f): f
Enter gender for anil (m/f): m
Enter gender for annu (m/f): f
Enter gender for suraj (m/f): m
Enter gender for khushi (m/f): f
Enter gender for swastika (m/f): f
Enter gender for anurag (m/f): m
Enter gender for gaurav (m/f): m
Enter gender for sujal (m/f): m
Enter gender for nehab (m/f): m
Enter gender for preeti (m/f): f
Enter gender for neha (m/f): f
Enter gender for diwas (m/f): m
Enter gender for anuja (m/f): f
Enter gender for inoj (m/f): m
Enter gender for dhrub (m/f): m
Enter gender for safal (m/f): m
Enter gender for prateek (m/f): m
Enter gender for pratik (m/f): m
Enter gender for samyog (m/f): m
Enter gender for prajeeta (m/f): f
Enter gender for sashmin (m/f): m
Enter gender for subhas (m/f): m
Enter gender for himanshu (m/f): m
Enter gender for aayush (m/f): m
Enter gender for sudip (m/f): m
Enter gender for gautam (m/f): m
Enter gender for prachit (m/f): m
Enter gender for binisha (m/f): f
Enter gender for lalan (m/f): m
Enter gender for ditish (m/f): m
Enter gender for suyog (m/f): m
Enter gender for bikash (m/f): m
Enter gender for estella (m/f): f
Enter gender for chhaya (m/f): f
Enter gender for naina (m/f): f
Enter gender for santosh (m/f): m
Enter gender for awanish (m/f): m
Enter gender for yogesh (m/f): m
Enter gender for abhishek (m/f): m
Enter gender for manish (m/f): m
Enter gender for pawan (m/f): m
Enter gender for rahul (m/f): m
Enter gender for rohan (m/f): m
Enter gender for abhijit (m/f): m
Enter gender for shweta (m/f): f
Enter gender for uddhav (m/f): m
Enter gender for ayush (m/f): m
Enter gender for bishal (m/f): m
Enter gender for sumnima (m/f): f
Enter gender for nirnaya (m/f): m
Enter gender for prasanna (m/f): m
Enter gender for prajwal (m/f): m
Enter gender for yogendra (m/f): m
Enter gender for shuyash (m/f): m
Enter gender for mausam (m/f): f
Enter gender for anugya (m/f): m
Enter gender for enjila (m/f): f
Enter gender for bimal (m/f): m
Enter gender for om (m/f): m
Enter gender for nischal (m/f): m
Enter gender for dev (m/f): m
Enter gender for rabindra (m/f): m
Enter gender for ganesh (m/f): m
Enter gender for nabin (m/f): m
Enter gender for sugam (m/f): m
Enter gender for aakash (m/f): m
Enter gender for prashanna (m/f): m
Enter gender for sabin (m/f): m
Enter gender for aayushree (m/f): f
Enter gender for shikha (m/f): f
Enter gender for kshitiz (m/f): m
Enter gender for cosmic (m/f): m
Enter gender for bidhan (m/f): m
Enter gender for prashamsa (m/f): f
Enter gender for shishir (m/f): m
Enter gender for shreejan (m/f): m
Enter gender for asmit (m/f): m
Enter gender for sthapana (m/f): f
Enter gender for surendra (m/f): m
Enter gender for prabin (m/f): m
Enter gender for isha (m/f): f
Enter gender for sarad (m/f): m
Enter gender for tanka (m/f): m
Enter gender for kripa (m/f): f
Enter gender for naveen (m/f): m
Enter gender for birat (m/f): m
Enter gender for darpan (m/f): m
Enter gender for bipul (m/f): m
Enter gender for subash (m/f): m
Enter gender for aasna (m/f): f
Enter gender for prabal (m/f): m
Enter gender for bibek (m/f): m
Enter gender for biplov (m/f): m
Enter gender for rijan (m/f): m
Enter gender for supriya (m/f): f
Enter gender for aliza (m/f): m
Enter gender for pratyush (m/f): m
Enter gender for roshan (m/f): m
Enter gender for umesh (m/f): m
Enter gender for gaurab (m/f): m
Enter gender for nirika (m/f): f
Enter gender for prashant (m/f): m
Enter gender for bhawana (m/f): f
Enter gender for sumin (m/f): m
Enter gender for ayushma (m/f): f
Enter gender for prasil (m/f): m
Enter gender for pratima (m/f): f
Enter gender for sopnil (m/f): m
Enter gender for bibhav (m/f): m
Enter gender for sona (m/f): f
Enter gender for rohit (m/f): m
Enter gender for abhi (m/f): m
Enter gender for dikshit (m/f): m
Enter gender for dibya (m/f): m
Enter gender for biraj (m/f): m
Enter gender for sadiksha (m/f): f
Enter gender for arpan (m/f): m
Enter gender for ashok (m/f): m
Enter gender for sakshi (m/f): f
Enter gender for bimarsh (m/f): m
Enter gender for pramit (m/f): m
Enter gender for sahil (m/f): m
Enter gender for abhisam (m/f): m
Enter gender for siddhant (m/f): m
Enter gender for anup (m/f): m
Enter gender for sneha (m/f): f
Enter gender for ankoor (m/f): m
Enter gender for apil (m/f): m
Enter gender for subidha (m/f): f
Enter gender for miraj (m/f): m
Enter gender for raj (m/f): m
Enter gender for shudan (m/f): m
Enter gender for grishma (m/f): f
Enter gender for sanskar (m/f): m
Enter gender for shiba (m/f): m
Enter gender for sandesh (m/f): m
Enter gender for junika (m/f): f
Enter gender for aman (m/f): m
Enter gender for sagar (m/f): m
Enter gender for sujan (m/f): m
Enter gender for sristi (m/f): f
Enter gender for nawaraj (m/f): m
Enter gender for dhiraj (m/f): m
Enter gender for rishek (m/f): m
Enter gender for kamalesh (m/f): m
Enter gender for sachin (m/f): m
Enter gender for hari (m/f): m
Enter gender for anish (m/f): m
Enter gender for abhinab (m/f): m
Enter gender for kushal (m/f): m
Enter gender for sankalp (m/f): m
Enter gender for aachal (m/f): f
Enter gender for dipesh (m/f): m
Enter gender for rifat (m/f): m
Enter gender for chetan (m/f): m
Enter gender for prashamshya (m/f): f
Enter gender for pujan (m/f): m
Enter gender for smarika (m/f): f
Enter gender for seema (m/f): f
Enter gender for ashim (m/f): m
Enter gender for rajesh (m/f): m
Enter gender for shreyash (m/f): m
Enter gender for pragyan (m/f): m
Enter gender for kritika (m/f): f
Enter gender for prithak (m/f): m
Enter gender for pranjal (m/f): m
Enter gender for sushant (m/f): m
Enter gender for junu (m/f): f
Enter gender for suprem (m/f): m
Enter gender for elsan (m/f): m
Enter gender for aashika (m/f): f
Enter gender for rabina (m/f): f
Enter gender for sandeep (m/f): m
Enter gender for nishant (m/f): m
Enter gender for aparna (m/f): f
Enter gender for bishant (m/f): m
Enter gender for bhupendra (m/f): m
Enter gender for hitesh (m/f): m
Enter gender for binayak (m/f): m
Enter gender for niket (m/f): m
Enter gender for samir (m/f): m
Enter gender for devish (m/f): m
Enter gender for samip (m/f): m
Enter gender for mahendra (m/f): m
Enter gender for aarogya (m/f): m
Enter gender for sulab (m/f): m
Enter gender for richa (m/f): f
Enter gender for binit (m/f): m
Enter gender for prince (m/f): m
Enter gender for chirayu (m/f): m
Enter gender for nishan (m/f): m
Enter gender for gopal (m/f): m
Enter gender for diwash (m/f): m
Enter gender for shashank (m/f): m
Enter gender for yalson (m/f): m
Enter gender for riwaj (m/f): m
Enter gender for sabhya (m/f): f
Enter gender for piyush (m/f): m
Enter gender for aniket (m/f): m
Enter gender for saugat (m/f): m
Enter gender for prerana (m/f): f
Enter gender for shambhu (m/f): m
Enter gender for amlesh (m/f): m
Enter gender for bishesh (m/f): m
Enter gender for manjil (m/f): m
Enter gender for bibhushan (m/f): m
Enter gender for namuna (m/f): f
Enter gender for anujaya (m/f): f
Enter gender for rajwala (m/f): m
Enter gender for rishab (m/f): m
Enter gender for rushal (m/f): m
Enter gender for suvrata (m/f): f
Enter gender for aastha (m/f): f
Enter gender for yuwen (m/f): m
Enter gender for anjila (m/f): f
Enter gender for saurabmalla (m/f): m
Enter gender for darshan (m/f): m
Enter gender for rojina (m/f): f
Enter gender for garima (m/f): f
Enter gender for shiksha (m/f): f
Enter gender for anmol (m/f): m
Enter gender for abhinaya (m/f): m
Enter gender for renisha (m/f): f
Enter gender for prasannata (m/f): m
Enter gender for mandip (m/f): m
Enter gender for aashraya (m/f): f
Enter gender for srijal (m/f): m
Enter gender for sabal (m/f): m
Enter gender for unnati (m/f): f

Enter gender for samikshya (m/f): f
Enter gender for mohan (m/f): m
Enter gender for sujen (m/f): m
Enter gender for ritu (m/f): f
Enter gender for rasdeep (m/f): m
Enter gender for purnima (m/f): f
Enter gender for krishna (m/f): m
Enter gender for madhusudan (m/f): m
Enter gender for dinesh (m/f): m
Enter gender for anupam (m/f): m
Enter gender for sangit (m/f): m
Enter gender for kalpit (m/f): m
Enter gender for siddhanta (m/f): m
Enter gender for romas (m/f): m
Enter gender for niraj (m/f): m
Enter gender for anjali (m/f): f
Enter gender for manoj (m/f): m
Enter gender for romie (m/f): m
Enter gender for sampada (m/f): f
Enter gender for rabin (m/f): m
Enter gender for ojashwi (m/f): f
Enter gender for hrishav (m/f): m
Enter gender for faruka (m/f): f
Enter gender for achyut (m/f): m
Enter gender for rakesh (m/f): m
Enter gender for shubham (m/f): m
Enter gender for bisham (m/f): m
Enter gender for lakhan (m/f): m
Enter gender for srijana (m/f): f
Enter gender for akito (m/f): m
Enter gender for ankit (m/f): m
Enter gender for arun (m/f): m
Enter gender for nirdeshika (m/f): f
Enter gender for puja (m/f): f
Enter gender for bikalpa (m/f): m
Enter gender for ronish (m/f): m
Enter gender for prakash (m/f): m
Enter gender for manjit (m/f): m
Enter gender for ayusha (m/f): f
Enter gender for roshni (m/f): f
Enter gender for ranjan (m/f): m
Enter gender for sunny (m/f): m
Enter gender for ravi (m/f): m
Enter gender for ram (m/f): m
Enter gender for shreejal (m/f): m
Enter gender for smriti (m/f): f
Enter gender for rashmi (m/f): f
Enter gender for sundeep (m/f): m
Enter gender for pankaj (m/f): m
Enter gender for yajjyu (m/f): m
Enter gender for kristina (m/f): f
Enter gender for laxman (m/f): m
Enter gender for nirjara (m/f): f
Enter gender for subhash (m/f): m
Enter gender for kabi (m/f): m
Enter gender for soniya (m/f): f
Enter gender for riyan (m/f): m
Enter gender for subodh (m/f): m
Enter gender for lijima (m/f): f
Enter gender for ashraya (m/f): m
Enter gender for snehi (m/f): f
Enter gender for saksham (m/f): m
Enter gender for kritima (m/f): f
Enter gender for thyam (m/f): m
Enter gender for baldeep (m/f): m
Enter gender for keshav (m/f): m
Enter gender for jishan (m/f): m
Enter gender for aayusha (m/f): f
Enter gender for dilasha (m/f): f
Enter gender for amartyaswor (m/f): m
Enter gender for rija (m/f): f
Enter gender for birendra (m/f): m
Enter gender for shristi (m/f): f
Enter gender for dipika (m/f): f
Enter gender for aaditya (m/f): m
Enter gender for rishap (m/f): m
Enter gender for basant (m/f): m
Enter gender for sudesh (m/f): m
Enter gender for kriti (m/f): f
Enter gender for tisha (m/f): f
Enter gender for rashika (m/f): f
Enter gender for aalok (m/f): m
Enter gender for shyam (m/f): m
Enter gender for sukrit (m/f): m
Enter gender for sandhya (m/f): f
Enter gender for sapana (m/f): f
Enter gender for shreeyukta (m/f): f
Enter gender for shivam (m/f): m
Enter gender for bhawani (m/f): f
Enter gender for rajun (m/f): m\
Enter gender for rajun (m/f): m
Enter gender for sanaya (m/f): f
Enter gender for aditya (m/f): m
Enter gender for avinash (m/f): m
Enter gender for utsav (m/f): m
Enter gender for bikesh (m/f): m
Enter gender for pratush (m/f): m
Enter gender for simran (m/f): f
Enter gender for pratyoos (m/f): m
Enter gender for shreeya (m/f): f
Enter gender for impress (m/f): m
Enter gender for saurav (m/f): m
Enter gender for krish (m/f): m
Enter gender for rubin (m/f): m
Enter gender for subhikshya (m/f): f
Enter gender for shankar (m/f): m
Enter gender for sahanaj (m/f): m
Enter gender for avinav (m/f): m
Enter gender for suyasha (m/f): f
Enter gender for roma (m/f): f
Enter gender for indus (m/f): m
Enter gender for pooja (m/f): f
Enter gender for subhashish (m/f): m
Enter gender for sarina (m/f): f
Enter gender for ashutosh (m/f): m
Enter gender for shruti (m/f): f
Enter gender for hridayanshu (m/f): m
Enter gender for aaradhya (m/f): m
Enter gender for bidhyasagar (m/f): m
Enter gender for roshil (m/f): m
Enter gender for shaligram (m/f): m
Enter gender for rishav (m/f): m
Enter gender for samaya (m/f): m
Enter gender for jiwan (m/f): m
Enter gender for lokendra (m/f): m
Enter gender for roman (m/f): m
Enter gender for lalit (m/f): m
Enter gender for rosy (m/f): f
Enter gender for sulav (m/f): m
Enter gender for denny (m/f): m
Enter gender for aarya (m/f): f
Enter gender for pranisha (m/f): m
Enter gender for hridayandra (m/f): m
Enter gender for hemanshu (m/f): m
Enter gender for usha (m/f): f
Enter gender for rajit (m/f): m
Enter gender for amulya (m/f): m
Enter gender for dikshant (m/f): m
Enter gender for nimesh (m/f): m
Enter gender for abhinav (m/f): m
Enter gender for homnath (m/f): m
Enter gender for suyash (m/f): m
Enter gender for prasis (m/f): m
Enter gender for sadikshya (m/f): f
Enter gender for sanjip (m/f): m
Enter gender for deewa (m/f): f
Enter gender for swarnim (m/f): m
Enter gender for ishashree (m/f): f
Enter gender for harikrishna (m/f): m
Enter gender for palistha (m/f): f
Enter gender for kaushal (m/f): m
Enter gender for charwi (m/f): m
Enter gender for spandan (m/f): m
Enter gender for avishek (m/f): m
Enter gender for asim (m/f): m
Enter gender for seewani (m/f): f
Enter gender for kaustuv (m/f): m
Enter gender for anuj (m/f): m
Enter gender for aadarsha (m/f): m
Enter gender for awiral (m/f): m
Enter gender for rujin (m/f): m
Enter gender for nirwan (m/f): m
Enter gender for riya (m/f): f
Enter gender for narayan (m/f): m
Enter gender for pramod (m/f): m
Enter gender for aarav (m/f): m
Enter gender for sahid (m/f): m
Enter gender for nishchal (m/f): m
Enter gender for roja (m/f): f
Enter gender for shirish (m/f): m
Enter gender for jeena (m/f): f
Enter gender for binu (m/f): f
Enter gender for bhaskar (m/f): m
Enter gender for shivang (m/f): m
Enter gender for milan (m/f): m
Enter gender for sahaj (m/f): m
Enter gender for fayeza (m/f): f
Enter gender for mamata (m/f): f
Enter gender for upendra (m/f): m
Enter gender for sakar (m/f): m
Enter gender for evika (m/f): f
Enter gender for rajish (m/f): m
Enter gender for khushboo (m/f): f
Enter gender for jastika (m/f): f
Enter gender for akshay (m/f): m
Enter gender for bipin (m/f): m
Enter gender for smritee (m/f): f
Enter gender for sadina (m/f): f
Enter gender for sadhana (m/f): f
Enter gender for abdul (m/f): m
Enter gender for jeeyas (m/f): m
Enter gender for laxmi (m/f): f
Enter gender for sumit (m/f): m
Enter gender for aakriti (m/f): f
Enter gender for tejendra (m/f): m
Enter gender for rajiv (m/f): m
Enter gender for swayaksha (m/f): f
Enter gender for purnika (m/f): f
Enter gender for muskan (m/f): f
Enter gender for liza (m/f): f
Enter gender for sital (m/f): m
Enter gender for binav (m/f): m
Enter gender for rupesh (m/f): m
Enter gender for abhishekh (m/f): m
Enter gender for prabhav (m/f): m
Enter gender for pratiksha (m/f): f
Enter gender for aaryan (m/f): m
Enter gender for sushil (m/f): m
Enter gender for rishikesh (m/f): m
Enter gender for apekshya (m/f): f
Enter gender for silvica (m/f): f
Enter gender for rajanand (m/f): m
Enter gender for akash (m/f): m
Enter gender for animesh (m/f): m
Enter gender for rejina (m/f): fm
Enter gender for rejina (m/f): f
Enter gender for rajani (m/f): f
Enter gender for niranjan (m/f): m
Enter gender for ainul (m/f): m
Enter gender for riik (m/f): m
Enter gender for shrijan (m/f): m
Enter gender for uchida (m/f): f
Enter gender for ajay (m/f): m
Enter gender for sworup (m/f): m
Enter gender for aayushma (m/f): f
Enter gender for kritan (m/f): m
Enter gender for ishwor (m/f): m
Enter gender for ragini (m/f): f
Enter gender for bishowdip (m/f): m
Enter gender for prasamsha (m/f): f
Enter gender for shubheksha (m/f): f
Enter gender for binaya (m/f): m
Enter gender for sitashma (m/f): f
Enter gender for shiv (m/f): m
Enter gender for aaryaman (m/f): m
Enter gender for brijesh (m/f): m
Enter gender for anima (m/f): f
Enter gender for chand (m/f): m
Enter gender for priyanka (m/f): f
Enter gender for dipisha (m/f): f
Enter gender for sandip (m/f): m
Enter gender for prasansa (m/f): f
Enter gender for sakchhyam (m/f): m
Enter gender for sachhyam (m/f): m
Enter gender for ruby (m/f): f
Enter gender for prachun (m/f): m

Enter gender for shristy (m/f): f
Enter gender for bishow (m/f): m
Enter gender for ashwini (m/f): f
Enter gender for abinash (m/f): m
Enter gender for aadesh (m/f): m
Enter gender for sitesh (m/f): m
Enter gender for resha (m/f): f
Enter gender for saumya (m/f): f
Enter gender for adarsha (m/f): m
Enter gender for tushar (m/f): m
Enter gender for nisma (m/f): f
Enter gender for atit (m/f): m
Enter gender for paras (m/f): m
Enter gender for prabesh (m/f): m
Enter gender for ritish (m/f): m
Enter gender for archisha (m/f): f
Enter gender for aashu (m/f): f
Enter gender for prashesh (m/f): m
Enter gender for lakpa (m/f): m
Enter gender for rachit (m/f): m
Enter gender for pradip (m/f): m
Enter gender for aagya (m/f): f
Enter gender for royal (m/f): m
Enter gender for krisha (m/f): f
Enter gender for akhilesh (m/f): m
Enter gender for dhan (m/f): m
Enter gender for aradhya (m/f): m
Enter gender for kamakshi (m/f): f
Enter gender for anusha (m/f): f
Enter gender for shraddha (m/f): f
Enter gender for vidhan (m/f): m
Enter gender for shekhar (m/f): m
Enter gender for raunak (m/f): m
Enter gender for siddharth (m/f): m
Enter gender for rashami (m/f): f
Enter gender for alish (m/f): m
Enter gender for jessica (m/f): f
Enter gender for prashanta (m/f): m
Enter gender for pallav (m/f): m
Enter gender for nirjal (m/f): m
Enter gender for ashesh (m/f): m
Enter gender for rikesh (m/f): m
Enter gender for prithu (m/f): f
Enter gender for mikchhiring (m/f): m
Enter gender for shanaya (m/f): f
Enter gender for kritisha (m/f): f
Enter gender for priyajan (m/f): f
Enter gender for yunika (m/f): f
Enter gender for shreevatsa (m/f): m
Enter gender for ishan (m/f): m
Enter gender for niyati (m/f): f
Enter gender for pratishthit (m/f): m
Enter gender for suniti (m/f): f
Enter gender for rujan (m/f): m
Enter gender for sindhu (m/f): f
Enter gender for subha (m/f): f
Enter gender for aashana (m/f): f
Enter gender for dibyansh (m/f): m
Enter gender for sheersa (m/f): f
Enter gender for gokarn (m/f): m
Enter gender for anamika (m/f): f
Enter gender for aditi (m/f): m
Enter gender for pradiksha (m/f): f
Enter gender for enish (m/f): m
Enter gender for sunayan (m/f): m
Enter gender for samyam (m/f): m
Enter gender for mukesh (m/f): m
Enter gender for anustha (m/f): f
Enter gender for amu (m/f): f
Enter gender for samragi (m/f): f
Enter gender for sakshyam (m/f): m
Enter gender for supurda (m/f): m
Enter gender for astuti (m/f): f
Enter gender for sunil (m/f): m
Enter gender for royas (m/f): m
Enter gender for alok (m/f): m
Enter gender for sonika (m/f): f
Enter gender for aabiskar (m/f): m
Enter gender for adheesh (m/f): m
Enter gender for darwin (m/f): m
Enter gender for biswas (m/f): m
Enter gender for nabindra (m/f): m
Enter gender for janak (m/f): m
Enter gender for swastik (m/f): m
Enter gender for aaron (m/f): m
Enter gender for bhagya (m/f): m
Enter gender for nugen (m/f): m
Enter gender for sashwot (m/f): m
Enter gender for aanchal (m/f): f
Enter gender for himanshi (m/f): f
Enter gender for subhakar (m/f): m
Enter gender for stuti (m/f): f
Enter gender for sameer (m/f): m
Enter gender for abal (m/f): m
Enter gender for sabina (m/f): f
Enter gender for ananya (m/f): m
Enter gender for nirmal (m/f): m
Enter gender for asahi (m/f): f
Enter gender for ajeet (m/f): m
Enter gender for unika (m/f): f
Enter gender for denish (m/f): m
Enter gender for radheshyam (m/f): m
Enter gender for pranshu (m/f): f
Enter gender for bishwas (m/f): m
Enter gender for amamul (m/f): m
Enter gender for unish (m/f): m
Enter gender for raghav (m/f): m
Enter gender for himal (m/f): m
Enter gender for ishab (m/f): m
Enter gender for utkrist (m/f): m
Enter gender for samriddhi (m/f): f
Enter gender for sashank (m/f): m
Enter gender for diksha (m/f): f
Enter gender for rizan (m/f): m
Enter gender for saimon (m/f): m
Enter gender for chhawi (m/f): f
Enter gender for sonu (m/f): f
Enter gender for samundra (m/f): f
Enter gender for dristi (m/f): f
Enter gender for prashil (m/f): m
Enter gender for bikal (m/f): m
Enter gender for kritazya (m/f): m
Enter gender for prasun (m/f): m
Enter gender for pulendra (m/f): m
Enter gender for banshika (m/f): f
Enter gender for sparsh (m/f): m
Enter gender for amit (m/f): m
Enter gender for biniv (m/f): m
Enter gender for swatantra (m/f): m
Enter gender for karuna (m/f): f
Enter gender for sanjay (m/f): m
Enter gender for sunim (m/f): m
Enter gender for saroj (m/f): m
Enter gender for srashta (m/f): f
Enter gender for jenik (m/f): m
Enter gender for ranjit (m/f): m
Enter gender for samarpan (m/f): m
Enter gender for suman (m/f): m
Enter gender for sunitee (m/f): f
Enter gender for vijay (m/f): m
Enter gender for pujita (m/f): f
Enter gender for gajendra (m/f): m
Enter gender for eshika (m/f): f
Enter gender for romee (m/f): f
Enter gender for arya (m/f): f
Enter gender for anush (m/f): m
Enter gender for kshitish (m/f): m
Enter gender for mikita (m/f): f
Enter gender for shrawon (m/f): m
Enter gender for anisha (m/f): f
Enter gender for ravindra (m/f): m
Enter gender for navin (m/f): m
Enter gender for aawaz (m/f): m
Enter gender for akriti (m/f): f
Enter gender for lumanti (m/f): f
Enter gender for anupama (m/f): f
Enter gender for dikshyanta (m/f): f
Enter gender for yuvraj (m/f): m
Enter gender for bharat (m/f): m
Enter gender for johan (m/f): m
Enter gender for bhagyarath (m/f): m
Enter gender for ajib (m/f): m
Enter gender for lokesh (m/f): m
Enter gender for manisha (m/f): f
Enter gender for bikram (m/f): m
Enter gender for ratneshwar (m/f): m
Enter gender for alin (m/f): m
Enter gender for prasidha (m/f): m
Enter gender for tank (m/f): m
Enter gender for pratigya (m/f): m
Enter gender for lilaj (m/f): m
Enter gender for aarati (m/f): f
Enter gender for aavash (m/f): m
Enter gender for teena (m/f): f
Enter gender for pragya (m/f): f
Enter gender for lokman (m/f): m
Enter gender for tushaar (m/f): m
Enter gender for udaya (m/f): m
Enter gender for aadarsh (m/f): m
Enter gender for madhav (m/f): m
Enter gender for ronak (m/f): m
Enter gender for kabiraj (m/f): m
Enter gender for sobit (m/f): m
Enter gender for sharad (m/f): m
Enter gender for reina (m/f): f
Enter gender for amrita (m/f): f
Enter gender for ragee (m/f): f
Enter gender for pratistha (m/f): f
Enter gender for kirtan (m/f): m
Enter gender for neer (m/f): m
Enter gender for subham (m/f): m
Enter gender for naresh (m/f): m
Enter gender for pritaz (m/f): m
Enter gender for maansi (m/f): f
Enter gender for shailendra (m/f): m
Enter gender for kapil (m/f): m
Enter gender for sumina (m/f): f
Enter gender for asbin (m/f): m
Enter gender for paribesh (m/f): m
Enter gender for sambid (m/f): m
Enter gender for yangchen (m/f): m
Enter gender for sanjana (m/f): f
Enter gender for suyesh (m/f): m
Enter gender for rikrita (m/f): f
Enter gender for sauhardha (m/f): m
Enter gender for dendan (m/f): m
Enter gender for ashish (m/f): m
Enter gender for keshab (m/f): m
Enter gender for pranjit (m/f): m
Enter gender for reejul (m/f): f
Enter gender for ranjana (m/f): f
Enter gender for badal (m/f): m
Enter gender for nischhal (m/f): m
Enter gender for shafal (m/f): m
Enter gender for gyanendra (m/f): m
Enter gender for aryaman (m/f): m
Enter gender for dhurub (m/f): m
Enter gender for anshu (m/f): m
Enter gender for prajwol (m/f): m
Enter gender for dipendra (m/f): m
Enter gender for prayasa (m/f): f
Enter gender for prativa (m/f): f
Enter gender for simon (m/f): m
Enter gender for mandira (m/f): f
Enter gender for mohit (m/f): m
Enter gender for nikhil (m/f): m
Enter gender for subhava (m/f): f
Enter gender for samridhi (m/f): f
Enter gender for susan (m/f): m
Enter gender for rojin (m/f): m
Enter gender for sambodhan (m/f): m
Enter gender for krishma (m/f): f
Enter gender for lalita (m/f): m
Enter gender for hem (m/f): m
Enter gender for saujan (m/f):  m
Enter gender for saujan (m/f): m
Enter gender for ashmit (m/f): m
Enter gender for yunesh (m/f): m
Enter gender for giriraj (m/f): m
Enter gender for raman (m/f): m
Enter gender for bhishm (m/f): m
Enter gender for rajat (m/f): m
Enter gender for ritik (m/f): m
Enter gender for kritish (m/f): m
Enter gender for yunisha (m/f): f
Enter gender for pranaya (m/f): f

Enter gender for hridesh (m/f): m
Enter gender for suprim (m/f): m
Enter gender for sayuj (m/f): m
Enter gender for ojaswi (m/f): f
Enter gender for spreeha (m/f): f
Enter gender for james (m/f): m
Enter gender for anuska (m/f): f
Enter gender for alex (m/f): m
Enter gender for chandan (m/f): m
Enter gender for shree (m/f): f
Enter gender for nirajan (m/f): m
Enter gender for sagya (m/f): m
Enter gender for nipsha (m/f): f
Enter gender for trishala (m/f): f
Enter gender for sakshy (m/f): f
Enter gender for sankalpa (m/f): m
Enter gender for rakshya (m/f): f
Enter gender for uma (m/f): f
Enter gender for maya (m/f): f
Enter gender for kshitij (m/f): m
Enter gender for yubraj (m/f): m
Enter gender for chetana (m/f): f
Enter gender for somya (m/f): f
Enter gender for ankita (m/f): f
Enter gender for shaloni (m/f): f
Enter gender for ananda (m/f): m
Enter gender for prakalpa (m/f): m
Enter gender for sumira (m/f): f
Enter gender for aavas (m/f): m
Enter gender for drishti (m/f): f
Enter gender for melina (m/f): f
Enter gender for sirsha (m/f): f
Enter gender for acchividhu (m/f): f
Enter gender for sanskriti (m/f): f
Enter gender for binay (m/f): m
Enter gender for sanjita (m/f): f
Enter gender for shrejal (m/f): f
Enter gender for kul (m/f): m
Enter gender for samira (m/f): f
Enter gender for jenisha (m/f): f
Enter gender for kiran (m/f): m
Enter gender for uttam (m/f): m
Enter gender for meena (m/f): f
Enter gender for pratikshya (m/f): f
Enter gender for kalpana (m/f): f
Enter gender for sammit (m/f): m
Enter gender for sonia (m/f): f
Enter gender for dikshika (m/f): f
Enter gender for puspa (m/f): f
Enter gender for aashutosh (m/f): m
Enter gender for bibhu (m/f): m
Enter gender for aashik (m/f): m
Enter gender for jenny (m/f): f
Enter gender for sanchita (m/f): f
Enter gender for rhiddhi (m/f): f
Enter gender for aaras (m/f): m
Enter gender for samaksha (m/f): f
Enter gender for rajendra (m/f): m
Enter gender for swagat (m/f): m
Enter gender for surachi (m/f): f
Enter gender for manaswi (m/f): f
Enter gender for aaniya (m/f): f
Enter gender for aviyan (m/f): m
Enter gender for shaksham (m/f): m
Enter gender for shiva (m/f): m
Enter gender for anjil (m/f): m
Enter gender for baliram (m/f): m
Enter gender for govinda (m/f): m
Enter gender for nimta (m/f): m
Enter gender for queen (m/f): f
Enter gender for muna (m/f): f
Enter gender for sajina (m/f): f
Enter gender for shakti (m/f): m
Enter gender for bijeet (m/f): m
Enter gender for sudishya (m/f): f
Enter gender for swikar (m/f): m
Enter gender for vipran (m/f): m
Enter gender for swarup (m/f): m
Enter gender for pranish (m/f): m
Enter gender for yubin (m/f): m
Enter gender for devesh (m/f): m
Enter gender for suyasa (m/f): f
Enter gender for shrajeela (m/f): f
Enter gender for saisa (m/f): f
Enter gender for satwik (m/f): m
Enter gender for bronisha (m/f): f
Enter gender for rodish (m/f): m
Enter gender for utkristha (m/f): f
Enter gender for ragosh (m/f): m
Enter gender for saleel (m/f): m
Enter gender for rajkumar (m/f): m
Enter gender for prasansha (m/f): f
Enter gender for kohinoor (m/f): f
Enter gender for hritik (m/f): m
Enter gender for kabita (m/f): m
Enter gender for aashif (m/f): m
Enter gender for sudikshya (m/f): f
Enter gender for samrat (m/f): m
Enter gender for saman (m/f): m
Enter gender for navnit (m/f): m
Enter gender for sanjeet (m/f): m
Enter gender for dikshya (m/f): f
Enter gender for krishala (m/f): f
Enter gender for utshav (m/f): m
Enter gender for shikhar (m/f): m
Enter gender for barsha (m/f): m

In [ ]:
df.groupby('Name')