In [2]:
import pandas as pd
import tabula as tb

In [3]:
# path_2022 = '/home/atrocity101/Desktop/repos/pandas/kucbt_eda/pdf/KUCBT_Final_Score_20221669868171.pdf'
# path_2023 = '/home/atrocity101/Desktop/repos/pandas/kucbt_eda/pdf/CBT_Score_with_Prog_2023_09_15_Print1694768486.pdf'
# path_2024 = '/home/atrocity101/Desktop/repos/pandas/kucbt_eda/pdf/CBT_Pass_List_2024_1_sept1725180337.pdf'
# path_2025 = '/home/atrocity101/Desktop/repos/pandas/kucbt_eda/pdf/KUCAT_CBT_2025_Rank_List.pdf'
ce_path_2025 = '/home/atrocity101/Desktop/repos/pandas/kucbt_eda/pdf/KUCAT-CBT-2025-CE.pdf'

In [4]:
# dfs_2022 = tb.read_pdf(path_2022, pages = 'all', stream=True, pandas_options = {'header':None})
# dfs_2023 = tb.read_pdf(path_2023, pages = 'all', lattice = True)
# dfs_2024 = tb.read_pdf(path_2024, pages = 'all', lattice = True)
# dfs_2025 = tb.read_pdf(path_2025, pages = 'all', lattice = True)
dfs_2025_ce = tb.read_pdf(ce_path_2025, pages = 'all', lattice = True)

In [5]:
dfs_2025_ce[0].head()

   S. No.        KUCBT No.                    Name  CBT Score
0       1  KUCBT_2025_2650            Sumyak Limbu       1543
1       2  KUCBT_2025_1451           Prabin Dhakal       1522
2       3  KUCBT_2025_1750             Sudivya Sah       1515
3       4   KUCBT_2025_849           Aavash Uprety       1500
4       5   KUCBT_2025_450  Chandan Kumar Panjiyar       1493

In [ ]:
#Discarding 2025 as it doesn't have score

In [6]:
for i,d in enumerate(dfs_2025_ce):
    print(f"Page{i+1}: ${d.shape} and columns -> {list(d.columns)}")

Page1: $(41, 4) and columns -> ['S. No.', 'KUCBT No.', 'Name', 'CBT Score']
Page2: $(42, 4) and columns -> ['S. No.', 'KUCBT No.', 'Name', 'CBT Score']
Page3: $(42, 4) and columns -> ['S. No.', 'KUCBT No.', 'Name', 'CBT Score']
Page4: $(42, 4) and columns -> ['S. No.', 'KUCBT No.', 'Name', 'CBT Score']
Page5: $(42, 4) and columns -> ['S. No.', 'KUCBT No.', 'Name', 'CBT Score']
Page6: $(42, 4) and columns -> ['S. No.', 'KUCBT No.', 'Name', 'CBT Score']
Page7: $(42, 4) and columns -> ['S. No.', 'KUCBT No.', 'Name', 'CBT Score']
Page8: $(42, 4) and columns -> ['S. No.', 'KUCBT No.', 'Name', 'CBT Score']
Page9: $(42, 4) and columns -> ['S. No.', 'KUCBT No.', 'Name', 'CBT Score']
Page10: $(42, 4) and columns -> ['S. No.', 'KUCBT No.', 'Name', 'CBT Score']
Page11: $(42, 4) and columns -> ['S. No.', 'KUCBT No.', 'Name', 'CBT Score']
Page12: $(42, 4) and columns -> ['S. No.', 'KUCBT No.', 'Name', 'CBT Score']
Page13: $(42, 4) and columns -> ['S. No.', 'KUCBT No.', 'Name', 'CBT Score']
Page14: $(42, 4) and columns -> ['S. No.', 'KUCBT No.', 'Name', 'CBT Score']
Page15: $(42, 4) and columns -> ['S. No.', 'KUCBT No.', 'Name', 'CBT Score']
Page16: $(42, 4) and columns -> ['S. No.', 'KUCBT No.', 'Name', 'CBT Score']
Page17: $(42, 4) and columns -> ['S. No.', 'KUCBT No.', 'Name', 'CBT Score']
Page18: $(42, 4) and columns -> ['S. No.', 'KUCBT No.', 'Name', 'CBT Score']
Page19: $(40, 4) and columns -> ['S. No.', 'KUCBT No.', 'Name', 'CBT Score']
Page20: $(41, 4) and columns -> ['S. No.', 'KUCBT No.', 'Name', 'CBT Score']
Page21: $(40, 4) and columns -> ['S. No.', 'KUCBT No.', 'Name', 'CBT Score']
Page22: $(42, 4) and columns -> ['S. No.', 'KUCBT No.', 'Name', 'CBT Score']
Page23: $(42, 4) and columns -> ['S. No.', 'KUCBT No.', 'Name', 'CBT Score']
Page24: $(6, 4) and columns -> ['S. No.', 'KUCBT No.', 'Name', 'CBT Score']

In [17]:
full_df = pd.concat(dfs_2025_ce, ignore_index = True)

In [18]:
full_df.columns

Index(['S. No.', 'KUCBT No.', 'Name', 'CBT Score'], dtype='object')

In [19]:
full_df.head()

   S. No.        KUCBT No.                    Name  CBT Score
0       1  KUCBT_2025_2650            Sumyak Limbu       1543
1       2  KUCBT_2025_1451           Prabin Dhakal       1522
2       3  KUCBT_2025_1750             Sudivya Sah       1515
3       4   KUCBT_2025_849           Aavash Uprety       1500
4       5   KUCBT_2025_450  Chandan Kumar Panjiyar       1493

In [27]:
full_df['Program'] = 'BE in Computer Engineering'
full_df

,KUCBT No.,Name,CBT Score,Program
0,KUCBT_2025_2650,Sumyak Limbu,1543,BE in Computer Engineering
1,KUCBT_2025_1451,Prabin Dhakal,1522,BE in Computer Engineering
2,KUCBT_2025_1750,Sudivya Sah,1515,BE in Computer Engineering
3,KUCBT_2025_849,Aavash Uprety,1500,BE in Computer Engineering
4,KUCBT_2025_450,Chandan Kumar Panjiyar,1493,BE in Computer Engineering
...,...,...,...,...
961,KUCBT_2025_1407,Mahim Lamichhane,296,BE in Computer Engineering
962,KUCBT_2025_2795,Manisha Bhatta,293,BE in Computer Engineering
963,KUCBT_2025_3187,Nitya Mishra,281,BE in Computer Engineering
964,KUCBT_2025_1264,Ganapati Ray,261,BE in Computer Engineering
965,KUCBT_2025_3196,Smarika Nepali,254,BE in Computer Engineering

In [28]:
full_df.columns = ['id', 'Name', 'KUCBT Score', 'Program']

In [29]:
full_df.head()

,id,Name,KUCBT Score,Program
0,KUCBT_2025_2650,Sumyak Limbu,1543,BE in Computer Engineering
1,KUCBT_2025_1451,Prabin Dhakal,1522,BE in Computer Engineering
2,KUCBT_2025_1750,Sudivya Sah,1515,BE in Computer Engineering
3,KUCBT_2025_849,Aavash Uprety,1500,BE in Computer Engineering
4,KUCBT_2025_450,Chandan Kumar Panjiyar,1493,BE in Computer Engineering

In [30]:
full_df.isna().sum()

id             0
Name           0
KUCBT Score    0
Program        0
dtype: int64

In [ ]:
#Do not touch within this boundary

In [31]:
full_df[full_df['Name'].isna()]

Empty DataFrame
Columns: [id, Name, KUCBT Score, Program]
Index: []

In [107]:
full_df = full_df.drop(index = 1784).copy()

In [ ]:
#Do not touch within this boundary

In [32]:
full_df.isna().sum()

id             0
Name           0
KUCBT Score    0
Program        0
dtype: int64

In [33]:
full_df.columns

Index(['id', 'Name', 'KUCBT Score', 'Program'], dtype='object')

In [34]:
full_df.dtypes

id             object
Name           object
KUCBT Score     int64
Program        object
dtype: object

In [35]:
full_df['KUCBT Score'].dtype

dtype('int64')

In [114]:
mask = full_df['KUCBT Score'].astype(str).str.contains('*', regex = False)
full_df[mask]

Empty DataFrame
Columns: [id, Name, KUCBT Score, Program]
Index: []

In [115]:
full_df['KUCBT Score'] = full_df['KUCBT Score'].astype(str).str.replace('*', '', regex=False).str.strip()

In [116]:
full_df['KUCBT Score'] = pd.to_numeric(full_df['KUCBT Score'], errors = 'coerce').astype('Int64')

In [117]:
full_df.dtypes

id             object
Name           object
KUCBT Score     Int64
Program        object
dtype: object

In [37]:
full_df.to_csv("./csv/version3/2025_final_ce.csv", index = False)

OSError: Cannot save file into a non-existent directory: 'csv/version3'